### ISSUE TITLE
feat: flutter_lints rules 추가

### ISSUE THREAD

**Issue by CheolheeLee0** [cnu-bot/cnubot-client-app#16]
## Feature Description

- flutter_lints 에 규칙 추가

## Todo list

- [x] 규칙 리스트 검색
- [x] 적용할 규칙 선정
- [x] 규칙 바탕으로 코드 수정

**Comment by ChanhyukPark-Tech** [comment]
thx
