### ISSUE TITLE
feat: 소식 페이지 API 연동

### ISSUE THREAD

**Issue by CheolheeLee0** [cnu-bot/cnubot-client-app#18]
## Feature Description

소식 페이지 API 연동하기

### 백마광장 게시판
news('새소식', 'NEWS'),
academicInformation('학사정보', 'ACADEMIC_INFO'),
cnuNews('CNU뉴스', 'CNU_NEWS'),
educationalInformation('교육정보', 'EDUCATION_INFO'),
businessGroupStartupAndEducation('사업단 창업, 교육', 'BUSINESS_GROUP_STARTUP'),
recruitmentAndInvitation('채용/초빙', 'RECRUIT_INVITATION'),
univCultureField('대학문화마당', 'UNIV_CULTURE_FIELD'),
cnuMarket('CNU장터', 'CNU_MARKET'),
jobSearch('구인', 'JOB_SEARCH'),
jobOffer('구직', 'JOB_OFFER'),
studyCompetition('스터디 및 공모전', 'STUDY_COMPETITION'),

### 국제교류본부 게시판
studentRecruiting('Student Recruiting', 'STUDENT_RECRUIT'),
event('Event', 'EVENT'),
jobAndCareer('Job&Career', 'JOB_CAREER'),
formAndData('Form&Data', 'FORM_DATA'),

## Todo list

- [x] 데이터 가져올 API 확인
- [x] 게시판 별 Query Parameter 확인
- [x] API Response 필드 확인
- [x] 소식 게시판의 게시글 모델 생성
- [x] UI에 보여줄 값 확인
- [x] API 연동 개발

**Comment by ChanhyukPark-Tech** [comment]
감사합니다!!!
