### ISSUE TITLE
[학식] 페이지 UI 퍼블리싱

### ISSUE THREAD

**Issue by CheolheeLee0** [cnu-bot/cnubot-client-app#21]
## Feature Description

학식 페이지 UI 퍼블리싱

![image](https://user-images.githubusercontent.com/78692286/204342019-4597758d-c62e-4fa5-b750-fffbfaac308e.png)

![image](https://user-images.githubusercontent.com/78692286/204342081-e24fcdab-1ce3-4ab7-acb1-de456cf42fc9.png)

## Todo list

- [x] 운영시간 데이터 저장 (json)
- [x] enum 만들기 (식당, 요일, 메뉴타입)
- [x] 공통 컴포넌트 위젯 만들기
