### ISSUE TITLE
[학식] 페이지 API 연동

### ISSUE THREAD

**Issue by CheolheeLee0** [cnu-bot/cnubot-client-app#23]
### 소식 페이지 API 연동하기

- 2, 3, 4학, 긱사, 생과대 API 연동
- 1학 API 연동

## Todo list

- [x] 데이터 가져올 API 확인
- [x] 식당별 Query Parameter 확인
- [x] API Response 필드 확인
- [x] 학식 화면의 음식, 식단 모델 생성
- [x] UI에 보여줄 값 확인
- [x] API 연동 개발
